chore: update VM image
GoogleCloudPlatform/anthos-samples pull request #483
Opened 2022-11-08 01:27 UTC by apeabody

#### Description
- Update the focal release used by the VM image

2022-11-14 19:24 UTC, ahrarmonsur requested changes
Hello @apeabody, thank you very much for the PR. There is a unit test related to the image name that is failing due to the introduced changes. Please adjust the test and include it in the PR.

In the future, it may be easier to run the tests locally to validate a change. Thank you!

```
main_test.go:361: 
        	Error Trace:	/home/shabirmean/actions-runner/_work/anthos-samples/anthos-samples/anthos-bm-gcp-terraform/test/unit/main_test.go:361
        	Error:      	Not equal: 
        	            	expected: "ubuntu-2004-focal-v20210429"
        	            	actual  : "ubuntu-2004-focal-v20221018"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-ubuntu-2004-focal-v20210429
        	            	+ubuntu-2004-focal-v20221018
        	Test:       	TestUnit_MainScript_ValidateDefaults
        	Messages:   	Variable does not match expected default value: image.
```

2022-11-14 19:44 UTC, apeabody commented
Thanks @ahrarmonsur!  Hadn't had a chance to get back to this, but I just updated the test.  Cheers!

2023-01-04 22:25 UTC, apeabody commented
Hi @ahrarmonsur & @shabirmean - Anything else needed for this?  Cheers!

2023-01-25 20:39 UTC, Shabirmean approved these changes

2023-01-25 22:52 UTC, ahrarmonsur approved these changes

2023-01-26 02:04 UTC, merged