update anthos versions
GoogleCloudPlatform/anthos-samples pull request #538
Opened 2022-12-26 20:05 UTC by bkauf

Changed Anthos versions for AWS/Azure to 1.25 latest patch

2022-12-27 19:15 UTC, VeraQin approved these changes

2022-12-28 16:36 UTC, hdp617 approved these changes

2023-01-26 16:39 UTC, Shabirmean requested changes
Need to add license headers

2023-01-31 20:02 UTC, Shabirmean commented on anthos-multi-cloud/AWS/terraform.tfvars
> +gcp_project_id = "anthos-multi-cloud-335819"
Is this correct? Seems like a personal project here.

2023-01-31 20:28 UTC, Shabirmean commented
Closing this because there is no response from @bkauf . I've copied the changes to a separate PR https://github.com/GoogleCloudPlatform/anthos-samples/pull/561 and fixed some of the issues here

2023-01-31 20:28 UTC, closed without merging